#!/bin/bash
source /usr/share/yunohost/helpers
current_date=$(date +"%d/%m/%Y %T")
notif="$current_date : Domain $1 added"
curl -X POST "__GOTIFYPATH__/message?token=__TOKEN__" -F "title=__SERVER__ - Domains" -F "message=$notif" > /dev/null 2>&1
