#!/bin/bash
source /usr/share/yunohost/helpers
current_date=$(date +"%d/%m/%Y %T")
id=$YNH_APP_ID
current_version=$YNH_APP_MANIFEST_VERSION
notif="$current_date : App : $id $current_version installed successfully"
curl -X POST "__GOTIFYPATH__/message?token=__TOKEN__" -F "title=__SERVER__ - App Install" -F "message=$notif" > /dev/null 2>&1
